# Generated by Django 4.2.7 on 2024-04-17 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_app', '0010_remove_eventlist_date_time_eventlist_date_and_more'),
        ('users_app', '0003_alter_token_access_token_alter_token_refresh_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event_id', 'user_id', 'is_registered')},
        ),
    ]
