# Generated by Django 4.2.7 on 2024-04-17 00:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0010_remove_eventlist_date_time_eventlist_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0004_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='event_id',
            new_name='event_list_id',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event_list_id', 'user_id', 'is_registered')},
        ),
    ]
