# Generated by Django 4.2.7 on 2024-04-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория мероприятия',
                'verbose_name_plural': 'Категории мероприятий',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город проведения',
                'verbose_name_plural': 'Города проведения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True, verbose_name='Название мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=400, unique=True, verbose_name='Название места')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Место проведения мероприятия',
                'verbose_name_plural': 'Места проведения мероприятия',
                'unique_together': {('location_name', 'city_id')},
            },
        ),
    ]
