# Generated by Django 4.2.7 on 2024-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_city_options_alter_location_options_eventlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={'verbose_name': 'Список мероприятий', 'verbose_name_plural': 'Список мероприятий'},
        ),
        migrations.AddField(
            model_name='eventlist',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
