# Generated by Django 4.2.7 on 2024-04-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_eventlist_options_eventlist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='events_app.city', verbose_name='Город'),
        ),
    ]
