# Generated by Django 4.2.7 on 2024-04-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_alter_location_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.city', verbose_name='Город'),
        ),
    ]
