# Generated by Django 4.2.7 on 2024-04-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_alter_location_location_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
